version: '2'
services:
  nomad-server-1:
    container_name: nomad-server-1
    command: /bin/nomad agent -config=/server.hcl
    environment:
      NOMAD_SERVER_HTTP_PORT: 4646
      NOMAD_SERVER_RPC_PORT: 4647
      NOMAD_SERVER_SERF_PORT: 4648
      NOMAD_SERVER_ADDRESS_2: nomad-server-1:5648
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6648
      NOMAD_DATA_DIR: /tmp/nomad/data/s1
    image: rms1000watt/nomad:latest
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    - /tmp:/tmp

  nomad-server-2:
    container_name: nomad-server-2
    command: /bin/nomad agent -config=/server.hcl
    environment:
      NOMAD_SERVER_HTTP_PORT: 5646
      NOMAD_SERVER_RPC_PORT: 5647
      NOMAD_SERVER_SERF_PORT: 5648
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4648
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6648
      NOMAD_DATA_DIR: /tmp/nomad/data/s2
    image: rms1000watt/nomad:latest
    ports:
      - 5646:5646
      - 5647:5647
      - 5648:5648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1

  nomad-server-3:
    container_name: nomad-server-3
    command: /bin/nomad agent -config=/server.hcl
    environment:
      NOMAD_SERVER_HTTP_PORT: 6646
      NOMAD_SERVER_RPC_PORT: 6647
      NOMAD_SERVER_SERF_PORT: 6648
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4648
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5648
      NOMAD_DATA_DIR: /tmp/nomad/data/s3
    image: rms1000watt/nomad:latest
    ports:
      - 6646:6646
      - 6647:6647
      - 6648:6648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1

  nomad-client-1:
    container_name: nomad-client-1
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_HTTP_PORT: 4656
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4647
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5647
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6647
      NOMAD_DATA_DIR: /tmp/nomad/data/c1
    image: rms1000watt/nomad:latest
    privileged: true
    ports:
      - 4656:4656
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1
    - nomad-server-2
    - nomad-server-3

  nomad-client-2:
    container_name: nomad-client-2
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_HTTP_PORT: 5656
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4647
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5647
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6647
      NOMAD_DATA_DIR: /tmp/nomad/data/c2
    image: rms1000watt/nomad:latest
    privileged: true
    ports:
      - 5656:5656
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1
    - nomad-server-2
    - nomad-server-3

  nomad-client-3:
    container_name: nomad-client-3
    command: /bin/nomad agent -config=/client.hcl
    environment:
      NOMAD_CLIENT_HTTP_PORT: 6656
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4647
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5647
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6647
      NOMAD_DATA_DIR: /tmp/nomad/data/c3
    image: rms1000watt/nomad:latest
    privileged: true
    ports:
      - 6656:6656
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./client.hcl.tpl:/client.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1
    - nomad-server-2
    - nomad-server-3
    